import { Sparkles } from "lucide-react";

export default function AiSummary() {
  return (
    <div className="bg-white rounded-2xl p-5 lg:p-6 shadow-sm border border-slate-100">
      <div className="flex items-center gap-3 mb-5">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center flex-shrink-0 shadow-sm">
          <Sparkles className="w-5 h-5 text-white" />
        </div>
        <div>
          <h3 className="text-base font-semibold text-slate-800">
            Weekly AI Summary
          </h3>
          <p className="text-slate-400 text-xs">
            Generated by OpenGuardian AI · March 10, 2026
          </p>
        </div>
      </div>

      <div className="bg-gradient-to-br from-slate-50 to-indigo-50/40 rounded-xl p-4 lg:p-5 border border-slate-100/80">
        <p className="text-slate-600 text-sm leading-relaxed">
          This week{" "}
          <span className="font-semibold text-slate-800">Alex</span> maintained
          a mostly stable routine. Education activity continued to occur during
          school hours, which aligns well with established baseline patterns.
        </p>
        <p className="text-slate-600 text-sm leading-relaxed mt-2.5">
          Gaming activity increased notably during evening hours, reaching
          approximately{" "}
          <span className="font-semibold text-slate-800">4 hours on Saturday</span>{" "}
          — above the typical baseline of 1 hour per day. One late-night social
          interaction was flagged outside normal usage hours. No persistent
          concerning patterns were detected beyond these anomalies.
        </p>
        <p className="text-slate-600 text-sm leading-relaxed mt-2.5">
          Overall behavior stability score is{" "}
          <span className="font-semibold text-indigo-600">85%</span>, reflecting
          a{" "}
          <span className="font-semibold text-emerald-600">healthy baseline</span>{" "}
          with minor deviations worth monitoring next week.
        </p>
      </div>

      <div className="flex items-center gap-2 mt-4 text-xs text-slate-400">
        <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0" />
        <span>
          Analysis based on anonymized behavior patterns. No personal data is
          stored or shared.
        </span>
      </div>
    </div>
  );
}
